#property strict
#property version   "0.079"
#property description "EAGOLD - BUY/SELL independent machines - Rules 1 to 9 + Hedge R9 + Backtest Panel"

input int MagicNumber=1001;
input double Lot=0.01;
input double Multiplier=1.10;
input int DigitsLots=2;
input double LotIncrement=0.02;
input double MaxOpenLot=3.00;
input double TakeProfit=5.00;
input double SellProfit=30.00;
input double BasketLoss=100.00;
input int SpreadLimit=100;
input int WaitSeconds=0;
input double FirstStep=160.0;
input double MiniGrid1=250.0;
input double SmartGrid1=80.0;
input double RecoveryMinDistance=110.0;
input double MiniGrid2=80.0;
input double SmartGrid2=60.0;
input double PendingStepTrail=50.0;
input double BasketRestartStep=160.0;
input int MaxTrades=2000;
input bool EnableCloseBy=true;
input double BuyProgressionTolerance=10.0;
input bool EnableR9Hedge=true;
input double R9ExposureTriggerLots=1.00;
input double R9TriggerLotMinimum=0.00;
input double R9HedgeFraction=0.6666666667;
input double R9BalanceCap=0.50;

string EA_NAME="EAGOLD";
string PANEL_PREFIX="EAGOLD_BT_";
double g_panelMinProfit=0.0;
double g_panelMaxLots=0.0;
bool g_panelInitialized=false;
bool g_r9HedgeActive=false;
int g_r9ProcessedTickets[];

double PointsToPrice(double points){return(points*Point);}
double NormalizePrice(double price){return(NormalizeDouble(price,Digits));}
double NormalizeLot(double lot){if(lot<Lot)lot=Lot;if(MaxOpenLot>0.0&&lot>MaxOpenLot)lot=MaxOpenLot;return(NormalizeDouble(lot,DigitsLots));}
bool IsEAGOLDOrder(){return(OrderSymbol()==Symbol()&&OrderMagicNumber()==MagicNumber);}
int CountOrdersByType(int type){int count=0;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;if(OrderType()==type)count++;}return(count);}
int CountDirectionPositions(int direction){return(CountOrdersByType(direction==OP_BUY?OP_BUY:OP_SELL));}
int CountDirectionPending(int direction){return(CountOrdersByType(direction==OP_BUY?OP_BUYSTOP:OP_SELLSTOP));}
int CountEAGOLDOrders(){int count=0;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(IsEAGOLDOrder())count++;}return(count);}
double DirectionBasketProfit(int direction){int type=(direction==OP_BUY?OP_BUY:OP_SELL);double total=0.0;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;total+=OrderProfit()+OrderSwap()+OrderCommission();}return(total);}
double DirectionLots(int direction){int type=(direction==OP_BUY?OP_BUY:OP_SELL);double total=0.0;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;total+=OrderLots();}return(total);}
double ExposureLots(){return(MathAbs(DirectionLots(OP_BUY)-DirectionLots(OP_SELL)));}
int HeavyDirection(){double b=DirectionLots(OP_BUY),s=DirectionLots(OP_SELL);if(b>s)return(OP_BUY);if(s>b)return(OP_SELL);return(-1);}

void PanelCreate(){string bg=PANEL_PREFIX+"BG";if(ObjectFind(0,bg)<0){ObjectCreate(0,bg,OBJ_RECTANGLE_LABEL,0,0,0);ObjectSetInteger(0,bg,OBJPROP_CORNER,CORNER_RIGHT_UPPER);ObjectSetInteger(0,bg,OBJPROP_ANCHOR,ANCHOR_RIGHT_UPPER);ObjectSetInteger(0,bg,OBJPROP_XDISTANCE,8);ObjectSetInteger(0,bg,OBJPROP_YDISTANCE,8);ObjectSetInteger(0,bg,OBJPROP_XSIZE,250);ObjectSetInteger(0,bg,OBJPROP_YSIZE,390);ObjectSetInteger(0,bg,OBJPROP_BGCOLOR,clrBlack);ObjectSetInteger(0,bg,OBJPROP_COLOR,clrDimGray);ObjectSetInteger(0,bg,OBJPROP_BORDER_TYPE,BORDER_FLAT);ObjectSetInteger(0,bg,OBJPROP_SELECTABLE,false);ObjectSetInteger(0,bg,OBJPROP_SELECTED,false);ObjectSetInteger(0,bg,OBJPROP_HIDDEN,true);ObjectSetInteger(0,bg,OBJPROP_BACK,false);}}
void PanelCreateLabel(string id,int row,color clr){string name=PANEL_PREFIX+id;if(ObjectFind(0,name)>=0)return;ObjectCreate(0,name,OBJ_LABEL,0,0,0);ObjectSetInteger(0,name,OBJPROP_CORNER,CORNER_RIGHT_UPPER);ObjectSetInteger(0,name,OBJPROP_ANCHOR,ANCHOR_RIGHT_UPPER);ObjectSetInteger(0,name,OBJPROP_XDISTANCE,18);ObjectSetInteger(0,name,OBJPROP_YDISTANCE,18+row*17);ObjectSetInteger(0,name,OBJPROP_FONTSIZE,9);ObjectSetString(0,name,OBJPROP_FONT,"Consolas");ObjectSetInteger(0,name,OBJPROP_COLOR,clr);ObjectSetInteger(0,name,OBJPROP_SELECTABLE,false);ObjectSetInteger(0,name,OBJPROP_SELECTED,false);ObjectSetInteger(0,name,OBJPROP_HIDDEN,true);ObjectSetInteger(0,name,OBJPROP_BACK,false);}
void PanelSet(string id,string text,int row,color clr){string name=PANEL_PREFIX+id;PanelCreateLabel(id,row,clr);ObjectSetString(0,name,OBJPROP_TEXT,text);ObjectSetInteger(0,name,OBJPROP_COLOR,clr);}
void PanelDelete(){string ids[]={"BG","TITLE","SEP1","BUY","BUYPL","BUYT","SELL","SELLPL","SELLT","SEP2","TOTAL","MIN","LOTS","MAXLOTS","NET","PEND","PBUY","PSELL","HEDGE","HEDGE2","SEP3","TIME"};for(int i=0;i<ArraySize(ids);i++){string name=PANEL_PREFIX+ids[i];if(ObjectFind(0,name)>=0)ObjectDelete(name);}}
string PanelMoney(double value){return(DoubleToString(value,2));}
string PanelLots(double value){return(DoubleToString(value,2));}
void PanelUpdate(){PanelCreate();int buyCount=0,sellCount=0,buyPending=0,sellPending=0;double buyLots=0.0,sellLots=0.0,buyProfit=0.0,sellProfit=0.0;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type==OP_BUY){buyCount++;buyLots+=OrderLots();buyProfit+=OrderProfit()+OrderSwap()+OrderCommission();}else if(type==OP_SELL){sellCount++;sellLots+=OrderLots();sellProfit+=OrderProfit()+OrderSwap()+OrderCommission();}else if(type==OP_BUYSTOP)buyPending++;else if(type==OP_SELLSTOP)sellPending++;}double totalProfit=buyProfit+sellProfit,totalLots=buyLots+sellLots,netLots=buyLots-sellLots;int totalPending=buyPending+sellPending;if(!g_panelInitialized){g_panelMinProfit=totalProfit;g_panelMaxLots=totalLots;g_panelInitialized=true;}else{if(totalProfit<g_panelMinProfit)g_panelMinProfit=totalProfit;if(totalLots>g_panelMaxLots)g_panelMaxLots=totalLots;}int row=0;PanelSet("TITLE","EAGOLD  v0.079",row++,clrWhite);PanelSet("SEP1","==============================",row++,clrSilver);PanelSet("BUY",StringFormat("BUY   %3d pos   %6s lot",buyCount,PanelLots(buyLots)),row++,clrLime);PanelSet("BUYPL",StringFormat("P/L       %12s",PanelMoney(buyProfit)),row++,clrLime);PanelSet("BUYT",StringFormat("Target    %12s",PanelMoney(buyCount*TakeProfit)),row++,clrSilver);PanelSet("SELL",StringFormat("SELL  %3d pos   %6s lot",sellCount,PanelLots(sellLots)),row++,clrTomato);PanelSet("SELLPL",StringFormat("P/L       %12s",PanelMoney(sellProfit)),row++,clrTomato);PanelSet("SELLT",StringFormat("Target    %12s",PanelMoney(sellCount*TakeProfit)),row++,clrSilver);PanelSet("SEP2","==============================",row++,clrSilver);PanelSet("TOTAL",StringFormat("TOTAL P/L %12s",PanelMoney(totalProfit)),row++,clrWhite);PanelSet("MIN",StringFormat("MENOR P/L %11s",PanelMoney(g_panelMinProfit)),row++,clrYellow);PanelSet("LOTS",StringFormat("LOTES ATUAIS %9s",PanelLots(totalLots)),row++,clrWhite);PanelSet("MAXLOTS",StringFormat("MAIOR ACUM. %9s",PanelLots(g_panelMaxLots)),row++,clrYellow);PanelSet("NET",StringFormat("EXPOS. LIQ. %10s",PanelLots(netLots)),row++,clrWhite);PanelSet("PEND",StringFormat("PENDENTES     %6d",totalPending),row++,clrSilver);PanelSet("PBUY",StringFormat("BUY STOP      %6d",buyPending),row++,clrSilver);PanelSet("PSELL",StringFormat("SELL STOP     %6d",sellPending),row++,clrSilver);if(g_r9HedgeActive){int heavy=HeavyDirection();string side=(heavy==OP_BUY?"SELL":"BUY");PanelSet("HEDGE","HEDGE: ATIVO",row++,clrYellow);PanelSet("HEDGE2",StringFormat("BALANCEANDO %s  EXP %s",side,PanelLots(ExposureLots())),row++,clrYellow);}else{PanelSet("HEDGE","HEDGE: INATIVO",row++,clrSilver);PanelSet("HEDGE2",StringFormat("EXPOS. %s",PanelLots(ExposureLots())),row++,clrSilver);}PanelSet("SEP3","==============================",row++,clrSilver);PanelSet("TIME",TimeToString(TimeCurrent(),TIME_SECONDS),row++,clrSilver);ChartRedraw(0);}

int SendPending(int type,double price,double lots,string comment){RefreshRates();double stopLevel=MarketInfo(Symbol(),MODE_STOPLEVEL)*Point;price=NormalizePrice(price);lots=NormalizeLot(lots);if(type==OP_BUYSTOP&&price<=Ask+stopLevel)return(-1);if(type==OP_SELLSTOP&&price>=Bid-stopLevel)return(-1);ResetLastError();int ticket=OrderSend(Symbol(),type,lots,price,0,0,0,comment,MagicNumber,0,clrNONE);if(ticket<0)Print(EA_NAME," OrderSend failed. type=",type," error=",GetLastError()," comment=",comment);else Print(EA_NAME," pending created. ticket=",ticket," type=",type," price=",DoubleToString(price,Digits)," lot=",DoubleToString(lots,DigitsLots)," comment=",comment);return(ticket);}
int SendMarket(int type,double lots,string comment){RefreshRates();lots=NormalizeLot(lots);double price=(type==OP_BUY?Ask:Bid);ResetLastError();int ticket=OrderSend(Symbol(),type,lots,NormalizePrice(price),0,0,0,comment,MagicNumber,0,clrNONE);if(ticket<0)Print(EA_NAME," market send failed. type=",type," error=",GetLastError()," comment=",comment);else Print(EA_NAME," market created. ticket=",ticket," type=",type," lot=",DoubleToString(lots,DigitsLots)," comment=",comment);return(ticket);}
bool CloseMarketOrder(int ticket){if(!OrderSelect(ticket,SELECT_BY_TICKET,MODE_TRADES))return(false);if(!IsEAGOLDOrder())return(false);int type=OrderType();if(type!=OP_BUY&&type!=OP_SELL)return(false);RefreshRates();double price=(type==OP_BUY?Bid:Ask);ResetLastError();if(!OrderClose(ticket,OrderLots(),NormalizePrice(price),0,clrNONE)){Print(EA_NAME," market close failed. ticket=",ticket," error=",GetLastError());return(false);}return(true);}
bool DeletePendingOrder(int ticket){if(!OrderSelect(ticket,SELECT_BY_TICKET,MODE_TRADES))return(false);if(!IsEAGOLDOrder())return(false);int type=OrderType();if(type!=OP_BUYSTOP&&type!=OP_SELLSTOP)return(false);ResetLastError();if(!OrderDelete(ticket)){Print(EA_NAME," pending delete failed. ticket=",ticket," error=",GetLastError());return(false);}return(true);}
void CloseAllDirectionPending(int direction){int type=(direction==OP_BUY?OP_BUYSTOP:OP_SELLSTOP);for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;DeletePendingOrder(OrderTicket());}}

void CreateFirstOrdersIfFlat(){if(CountEAGOLDOrders()!=0)return;RefreshRates();int b=SendPending(OP_BUYSTOP,Ask+PointsToPrice(FirstStep),Lot,"EAGOLD R1 FIRST BUY");int s=SendPending(OP_SELLSTOP,Bid-PointsToPrice(FirstStep),Lot,"EAGOLD R1 FIRST SELL");if(b>0||s>0)Print(EA_NAME," RULE 1: initial seeds created. BUY=",b," SELL=",s);}

bool GetLatestActivatedPosition(int direction,double &latestPrice,double &latestLot,int &latestTicket){int type=(direction==OP_BUY?OP_BUY:OP_SELL);latestPrice=0.0;latestLot=NormalizeLot(Lot);latestTicket=-1;datetime latestTime=0;bool found=false;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;datetime t=OrderOpenTime();int ticket=OrderTicket();if(!found||t>latestTime||(t==latestTime&&ticket>latestTicket)){found=true;latestTime=t;latestPrice=OrderOpenPrice();latestLot=OrderLots();latestTicket=ticket;}}return(found);}
bool HasRecoveryPending(int direction){string tag=(direction==OP_BUY?"EAGOLD BUY RECOVERY":"EAGOLD SELL RECOVERY");int type=(direction==OP_BUY?OP_BUYSTOP:OP_SELLSTOP);for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;if(StringFind(OrderComment(),tag,0)>=0)return(true);}return(false);}
double NextRecoveryLot(double previousLot){if(previousLot<=0.0)return(NormalizeLot(Lot));return(NormalizeLot(previousLot*Multiplier+LotIncrement));}
void BuyRecovery(){if(SmartGrid1<=0.0||RecoveryMinDistance<=0.0)return;if(CountDirectionPositions(OP_BUY)<=0||HasRecoveryPending(OP_BUY))return;double p=0.0,l=Lot;int t=-1;if(!GetLatestActivatedPosition(OP_BUY,p,l,t))return;RefreshRates();if(p-Ask<PointsToPrice(2.0*SmartGrid1))return;double stop=NormalizePrice(Ask+PointsToPrice(RecoveryMinDistance));if(stop<=Ask+MarketInfo(Symbol(),MODE_STOPLEVEL)*Point)return;SendPending(OP_BUYSTOP,stop,NextRecoveryLot(l),"EAGOLD BUY RECOVERY");}
void SellRecovery(){if(SmartGrid1<=0.0||RecoveryMinDistance<=0.0)return;if(CountDirectionPositions(OP_SELL)<=0||HasRecoveryPending(OP_SELL))return;double p=0.0,l=Lot;int t=-1;if(!GetLatestActivatedPosition(OP_SELL,p,l,t))return;RefreshRates();if(Bid-p<PointsToPrice(2.0*SmartGrid1))return;double stop=NormalizePrice(Bid-PointsToPrice(RecoveryMinDistance));if(stop>=Bid-MarketInfo(Symbol(),MODE_STOPLEVEL)*Point)return;SendPending(OP_SELLSTOP,stop,NextRecoveryLot(l),"EAGOLD SELL RECOVERY");}

bool CanCloseLightBasket(int direction){double b=DirectionLots(OP_BUY),s=DirectionLots(OP_SELL);if(b==s)return(true);if(direction==OP_BUY&&b<s&&s>0.0)return(false);if(direction==OP_SELL&&s<b&&b>0.0)return(false);return(true);}

bool CloseDirectionPositionsRobust(int direction){int type=(direction==OP_BUY?OP_BUY:OP_SELL);int tickets[];ArrayResize(tickets,0);for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder()||OrderType()!=type)continue;int n=ArraySize(tickets);ArrayResize(tickets,n+1);tickets[n]=OrderTicket();}bool ok=true;for(int j=0;j<ArraySize(tickets);j++){if(!CloseMarketOrder(tickets[j]))ok=false;}return(ok&&CountDirectionPositions(direction)==0);}

void BuySingleTakeProfit(){if(CountDirectionPositions(OP_BUY)!=1)return;if(!CanCloseLightBasket(OP_BUY))return;if(DirectionBasketProfit(OP_BUY)<TakeProfit)return;int ticket=-1;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(IsEAGOLDOrder()&&OrderType()==OP_BUY){ticket=OrderTicket();break;}}if(ticket>0&&CloseMarketOrder(ticket)){CloseAllDirectionPending(OP_BUY);SendPending(OP_BUYSTOP,Ask+PointsToPrice(MiniGrid1),Lot,"EAGOLD R4 BUY NEXT");Print(EA_NAME," RULE 4 BUY TP REENTRY. closed=",ticket);}}
void SellSingleTakeProfit(){if(CountDirectionPositions(OP_SELL)!=1)return;if(!CanCloseLightBasket(OP_SELL))return;if(DirectionBasketProfit(OP_SELL)<TakeProfit)return;int ticket=-1;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(IsEAGOLDOrder()&&OrderType()==OP_SELL){ticket=OrderTicket();break;}}if(ticket>0&&CloseMarketOrder(ticket)){CloseAllDirectionPending(OP_SELL);SendPending(OP_SELLSTOP,Bid-PointsToPrice(MiniGrid2),Lot,"EAGOLD R4 SELL NEXT");Print(EA_NAME," RULE 4 SELL TP REENTRY. closed=",ticket);}}

bool BuyBasketClose(){int count=CountDirectionPositions(OP_BUY);if(count<=1||TakeProfit<=0.0)return(false);if(!CanCloseLightBasket(OP_BUY))return(false);double target=count*TakeProfit;double profit=DirectionBasketProfit(OP_BUY);if(profit<target)return(false);Print(EA_NAME," RULE 5 BUY TARGET. count=",count," profit=",DoubleToString(profit,2)," target=",DoubleToString(target,2));bool closed=CloseDirectionPositionsRobust(OP_BUY);if(closed){CloseAllDirectionPending(OP_BUY);Print(EA_NAME," RULE 5 BUY CLOSED ALL. count=",count);return(true);}Print(EA_NAME," RULE 5 BUY PARTIAL/FAILED. remaining=",CountDirectionPositions(OP_BUY));return(false);}
bool SellBasketClose(){int count=CountDirectionPositions(OP_SELL);if(count<=1||TakeProfit<=0.0)return(false);if(!CanCloseLightBasket(OP_SELL))return(false);double target=count*TakeProfit;double profit=DirectionBasketProfit(OP_SELL);if(profit<target)return(false);Print(EA_NAME," RULE 5 SELL TARGET. count=",count," profit=",DoubleToString(profit,2)," target=",DoubleToString(target,2));bool closed=CloseDirectionPositionsRobust(OP_SELL);if(closed){CloseAllDirectionPending(OP_SELL);Print(EA_NAME," RULE 5 SELL CLOSED ALL. count=",count);return(true);}Print(EA_NAME," RULE 5 SELL PARTIAL/FAILED. remaining=",CountDirectionPositions(OP_SELL));return(false);}

bool IntArrayContains(int &arr[],int ticket){for(int i=0;i<ArraySize(arr);i++)if(arr[i]==ticket)return(true);return(false);}
void IntArrayAdd(int &arr[],int ticket){if(ticket<0||IntArrayContains(arr,ticket))return;int n=ArraySize(arr);ArrayResize(arr,n+1);arr[n]=ticket;}
bool R9Processed(int ticket){return(IntArrayContains(g_r9ProcessedTickets,ticket));}
void R9MarkProcessed(int ticket){IntArrayAdd(g_r9ProcessedTickets,ticket);}
void R9SeedExistingPositions(){for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type==OP_BUY||type==OP_SELL)R9MarkProcessed(OrderTicket());}}

void TrailStopOrdersRule6(){if(SmartGrid1<=0.0||RecoveryMinDistance<=0.0||PendingStepTrail<=0.0)return;double trail=PointsToPrice(RecoveryMinDistance),step=PointsToPrice(PendingStepTrail),sl=MarketInfo(Symbol(),MODE_STOPLEVEL)*Point;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type!=OP_BUYSTOP&&type!=OP_SELLSTOP)continue;string c=OrderComment();if(StringFind(c,"EAGOLD BUY RECOVERY",0)<0&&StringFind(c,"EAGOLD SELL RECOVERY",0)<0)continue;RefreshRates();double cur=OrderOpenPrice(),desired=cur,movement=0.0;int ticket=OrderTicket();if(type==OP_SELLSTOP){desired=NormalizePrice(Bid-trail);movement=cur-desired;if(movement<step||desired>=cur||desired>=Bid-sl){if(movement>=step)Print(EA_NAME," RULE 6 SELL CHECK ticket=",ticket," cur=",DoubleToString(cur,Digits)," bid=",DoubleToString(Bid,Digits)," desired=",DoubleToString(desired,Digits)," movement=",DoubleToString(movement/Point,1));continue;}}else{desired=NormalizePrice(Ask+trail);movement=desired-cur;if(movement<step||desired<=cur||desired<=Ask+sl){if(movement>=step)Print(EA_NAME," RULE 6 BUY CHECK ticket=",ticket," cur=",DoubleToString(cur,Digits)," ask=",DoubleToString(Ask,Digits)," desired=",DoubleToString(desired,Digits)," movement=",DoubleToString(movement/Point,1));continue;}}ResetLastError();if(!OrderModify(ticket,desired,0,0,0,clrNONE))Print(EA_NAME," RULE 6 TRAIL FAILED ticket=",ticket," type=",(type==OP_BUY?"BUY STOP":"SELL STOP")," old=",DoubleToString(cur,Digits)," new=",DoubleToString(desired,Digits)," market=",DoubleToString(type==OP_BUY?Ask:Bid,Digits)," error=",GetLastError());else Print(EA_NAME," RULE 6 TRAIL ticket=",ticket," type=",(type==OP_BUY?"BUY STOP":"SELL STOP")," old=",DoubleToString(cur,Digits)," new=",DoubleToString(desired,Digits)," market=",DoubleToString(type==OP_BUY?Ask:Bid,Digits)," step=",DoubleToString(PendingStepTrail,2));}}

void TrailSpecialFirstStopOrders(){if(PendingStepTrail<=0.0)return;double sl=MarketInfo(Symbol(),MODE_STOPLEVEL)*Point;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type!=OP_BUYSTOP&&type!=OP_SELLSTOP)continue;string c=OrderComment();double baseStep=0.0;string family="";if(StringFind(c,"EAGOLD R1 FIRST",0)>=0){baseStep=FirstStep;family="R1 FIRST";}else if(StringFind(c,"EAGOLD R7 RESTART",0)>=0){baseStep=BasketRestartStep;family="R7 RESTART";}else continue;if(baseStep<=0.0)continue;double trail=PointsToPrice(baseStep),step=PointsToPrice(PendingStepTrail);RefreshRates();double cur=OrderOpenPrice(),desired=cur,movement=0.0;int ticket=OrderTicket();if(type==OP_SELLSTOP){desired=NormalizePrice(Bid-trail);movement=cur-desired;if(movement<step||desired>=cur||desired>=Bid-sl){if(movement>=step)Print(EA_NAME," RULE 7 SELL CHECK ticket=",ticket," family=",family," old=",DoubleToString(cur,Digits)," bid=",DoubleToString(Bid,Digits)," desired=",DoubleToString(desired,Digits)," movement=",DoubleToString(movement/Point,1));continue;}}else{desired=NormalizePrice(Ask+trail);movement=desired-cur;if(movement<step||desired<=cur||desired<=Ask+sl){if(movement>=step)Print(EA_NAME," RULE 7 BUY CHECK ticket=",ticket," family=",family," old=",DoubleToString(cur,Digits)," ask=",DoubleToString(Ask,Digits)," desired=",DoubleToString(desired,Digits)," movement=",DoubleToString(movement/Point,1));continue;}}ResetLastError();if(!OrderModify(ticket,desired,0,0,0,clrNONE))Print(EA_NAME," RULE 7 TRAIL FAILED ticket=",ticket," family=",family," old=",DoubleToString(cur,Digits)," new=",DoubleToString(desired,Digits)," market=",DoubleToString(type==OP_BUY?Ask:Bid,Digits)," error=",GetLastError());else Print(EA_NAME," RULE 7 TRAIL ticket=",ticket," family=",family," old=",DoubleToString(cur,Digits)," new=",DoubleToString(desired,Digits)," market=",DoubleToString(type==OP_BUY?Ask:Bid,Digits)," step=",DoubleToString(PendingStepTrail,2));}}
void RestartEmptyBasket(int direction){if(BasketRestartStep<=0.0)return;if(CountDirectionPositions(direction)!=0||CountDirectionPending(direction)!=0)return;RefreshRates();if(direction==OP_BUY)SendPending(OP_BUYSTOP,Ask+PointsToPrice(BasketRestartStep),Lot,"EAGOLD R7 RESTART BUY");else SendPending(OP_SELLSTOP,Bid-PointsToPrice(BasketRestartStep),Lot,"EAGOLD R7 RESTART SELL");}

bool R9GetNewExposureState(int &lightDirection,double &exposure,double &lightLots,double &heavyLots){double b=DirectionLots(OP_BUY),s=DirectionLots(OP_SELL);exposure=MathAbs(b-s);lightDirection=-1;lightLots=MathMin(b,s);heavyLots=MathMax(b,s);if(exposure<R9ExposureTriggerLots)return(false);if(b<s)lightDirection=OP_BUY;else if(s<b)lightDirection=OP_SELL;else return(false);return(true);}
bool R9HedgeFromActivatedTicket(int ticket){if(!EnableR9Hedge)return(false);if(!OrderSelect(ticket,SELECT_BY_TICKET,MODE_TRADES))return(false);if(!IsEAGOLDOrder())return(false);int type=OrderType();if(type!=OP_BUY&&type!=OP_SELL)return(false);double triggerLot=OrderLots();int light=-1;double exposure=0.0,lightLots=0.0,heavyLots=0.0;if(!R9GetNewExposureState(light,exposure,lightLots,heavyLots)){g_r9HedgeActive=false;return(false);}int heavy=HeavyDirection();if(type!=heavy)return(false);double hedgeLot=NormalizeLot(triggerLot*R9HedgeFraction);double maxHedge=NormalizeLot(exposure*R9BalanceCap);if(maxHedge<Lot)return(false);if(hedgeLot>maxHedge)hedgeLot=maxHedge;hedgeLot=NormalizeLot(hedgeLot);if(hedgeLot<=0.0)return(false);int hedgeTicket=SendMarket(light,hedgeLot,StringFormat("EAGOLD R9 HEDGE FROM #%d",ticket));if(hedgeTicket>0){R9MarkProcessed(hedgeTicket);g_r9HedgeActive=true;Print(EA_NAME," RULE 9 HEDGE: activation=",ticket," triggerLot=",DoubleToString(triggerLot,DigitsLots)," light=",(light==OP_BUY?"BUY":"SELL")," exposure=",DoubleToString(exposure,DigitsLots)," hedgeLot=",DoubleToString(hedgeLot,DigitsLots)," cap=",DoubleToString(R9BalanceCap,2)," newTicket=",hedgeTicket);return(true);}return(false);}
void Rule9DetectActivatedOrders(){if(!EnableR9Hedge)return;for(int i=OrdersTotal()-1;i>=0;i--){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES))continue;if(!IsEAGOLDOrder())continue;int type=OrderType();if(type!=OP_BUY&&type!=OP_SELL)continue;int ticket=OrderTicket();if(R9Processed(ticket))continue;R9HedgeFromActivatedTicket(ticket);R9MarkProcessed(ticket);}double exposure=ExposureLots();if(exposure<R9ExposureTriggerLots)g_r9HedgeActive=false;}

void BuyMachine(){bool basketClosed=BuyBasketClose();if(basketClosed)RestartEmptyBasket(OP_BUY);BuySingleTakeProfit();BuyRecovery();}
void SellMachine(){bool basketClosed=SellBasketClose();if(basketClosed)RestartEmptyBasket(OP_SELL);SellSingleTakeProfit();SellRecovery();}

int OnInit(){ArrayResize(g_r9ProcessedTickets,0);g_r9HedgeActive=false;g_panelInitialized=false;g_panelMinProfit=0.0;g_panelMaxLots=0.0;R9SeedExistingPositions();PanelUpdate();Print(EA_NAME," v0.079 initialized. R9=activation + exposure + balance cap, R5=robust directional basket close with light-basket protection, R6=Recovery trailing, R7=First/Restart trailing.");CreateFirstOrdersIfFlat();PanelUpdate();return(INIT_SUCCEEDED);}
void OnDeinit(const int reason){PanelDelete();}
void OnTick(){Rule9DetectActivatedOrders();BuyMachine();SellMachine();CreateFirstOrdersIfFlat();TrailStopOrdersRule6();TrailSpecialFirstStopOrders();PanelUpdate();}
